### ISSUE TITLE
Wrong type variable reported for polymorphic type alias

### ISSUE THREAD

**Issue by jefelino** [elm-lang/error-message-catalog#69]
```
type alias F a = a

wrong : F a -> F b
wrong = identity
```

This produces the following error message (Elm version 0.16).

```
The type annotation for `wrong` does not match its definition.
The type annotation is saying:
    F b -> F b
But I am inferring that the definition has this type:
    F b -> F b
Hint: A type annotation is clashing with itself or with a sub-annotation. This
can be particularly tricky, so read more about it.
<https://github.com/elm-lang/elm-compiler/blob/0.16.0/hints/type-annotations.md>
```

Note in contrast that this code produces the correct error message:

```
wrong' : a -> b
wrong' = identity
```

```
The type annotation for `wrong'` does not match its definition.
The type annotation is saying:
    a -> b
But I am inferring that the definition has this type:
    a -> a
```

**Comment by jvoigtlaender** [comment]
This looks like a true bug in the compiler, not a "this error message is technically correct, but could be better phrased/presented". This repository here is, as far as I know, meant for the latter kind of things (messages that are not buggy, but could be improved), not for compiler bugs. So I suggest you move this over to the https://github.com/elm-lang/elm-compiler repository. In fact, I guess that you have just encountered the same bug that others have already: https://github.com/elm-lang/elm-compiler/issues/1192. Maybe add your example to that issue, in case it is simpler than the examples already present there?

**Comment by jefelino** [comment]
Ok, thanks. I've posted a comment there.

**Comment by mgold** [comment]
Having done exactly this a few days ago, I think it speaks to our attitude about compilers: "Yeah it gave me a logically inconsistent error message, but that's 'not a real bug' somehow."

**Comment by jvoigtlaender** [comment]
This is supposed to be fixed now. See https://github.com/elm-lang/elm-compiler/issues/1192#issuecomment-215254480.

**Comment by rtfeldman** [comment]
Confirmed this is fixed in 0.17. Here is the current error message I get:

```
-- TYPE MISMATCH ---------------------------------------------------------------

The type annotation for `wrong` does not match its definition.

9| wrong : F a -> F b
           ^^^^^^^^^^
The type annotation is saying:

    F b -> F c

But I am inferring that the definition has this type:

    F b -> F b

Hint: A type annotation is clashing with itself or with a sub-annotation. This
can be particularly tricky, so read more about it.
<https://github.com/elm-lang/elm-compiler/blob/0.17.0/hints/type-annotations.md>
```

**Comment by jvoigtlaender** [comment]
Hmm, well, as https://github.com/elm-lang/elm-compiler/issues/1192#issuecomment-218848992 shows, the compiler bug underlying this is not really fixed. We just need a very small modification of the original example here and it still breaks.

But there is a corresponding issue in the compiler repo anyway.

**Comment by jvoigtlaender** [comment]
For the record, https://github.com/elm-lang/elm-compiler/issues/1371.
